person:
  user-name: wangwu
  boss: false
  birth: 2013/03/34 09:12:42
  age: 21
  pet: {name: dog}
  interests: [pingpang,draw,swing]
  animal:
    - dog
    - cat
  score:
    english:
      - 23
      - 22
    math: [3,2,]
  salarys: [21.32,644.7]
  all-pets:
    sick:
      - {name: fox}
      - {name: chicken}
    health:
      - {name: pick}
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/beimysql
    username: root
    password: beiyuan3721
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      aop-patterns: demo.controller.*  #监控SpringBean
#      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）
#
#      stat-view-servlet:   # 配置监控页功能
#        enabled: true
#        login-username: admin
#        login-password: admin
#        resetEnable: false
#
#      web-stat-filter:  # 监控web
#        enabled: true
#        urlPattern: /*
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#
#
#      filter:
#        stat:    # 对上面filters里面的stat的详细配置
#          slow-sql-millis: 1000
#          logSlowSql: true
#          enabled: true
#        wall:
#          enabled: true
#          config:
#            drop-table-allow: false
  jdbc:
    template:
      query-timeout: 1
  profiles:
    active: prod

#  mvc:
#    static-path-pattern: /res/**

#  resources:
mybatis:
#  config-location: classpath:mybatis/mybayis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#    static-locations: [classpath:/staticres/]

info:
  appName: boot-admin
  version: 2.0.1
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@
  mavenGroupId: @project.groupId@